import { NextResponse } from 'next/server';
import { createServerSupabaseClient, getUser, getUserProfile } from '@/lib/supabase/server';
import type { Profile } from '@/types';

interface RouteParams {
  params: Promise<{ id: string }>;
}

// POST - Make flow public and generate share link
export async function POST(request: Request, { params }: RouteParams) {
  const { id } = await params;
  const user = await getUser();

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Check Pro tier
  const profile = await getUserProfile() as Profile | null;
  if (profile?.subscription_tier !== 'paid') {
    return NextResponse.json(
      { error: 'Pro subscription required for sharing flows' },
      { status: 403 }
    );
  }

  const supabase = await createServerSupabaseClient();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any;

  // Verify ownership and get current state
  const { data: existingFlow, error: fetchError } = await db
    .from('flows')
    .select('id, is_public, public_slug')
    .eq('id', id)
    .eq('user_id', user.id)
    .single();

  if (fetchError || !existingFlow) {
    return NextResponse.json({ error: 'Flow not found' }, { status: 404 });
  }

  // Calculate expiration time (24 hours from now)
  const expiresAt = new Date();
  expiresAt.setHours(expiresAt.getHours() + 24);

  // If already public, reset the expiration and return existing slug
  if (existingFlow.is_public && existingFlow.public_slug) {
    // Reset the expiration time
    await db
      .from('flows')
      .update({
        share_expires_at: expiresAt.toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', id);

    return NextResponse.json({
      is_public: true,
      public_slug: existingFlow.public_slug,
      share_url: `${process.env.NEXT_PUBLIC_APP_URL || ''}/flow/${existingFlow.public_slug}`,
      expires_at: expiresAt.toISOString(),
    });
  }

  // Set is_public to true and expiration - the database trigger will generate the public_slug
  const { error: updateError } = await db
    .from('flows')
    .update({
      is_public: true,
      share_expires_at: expiresAt.toISOString(),
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (updateError) {
    console.error('Error making flow public:', updateError);
    return NextResponse.json({ error: updateError.message }, { status: 500 });
  }

  // Fetch the actual slug generated by the database trigger
  const { data: updatedFlow, error: fetchUpdatedError } = await db
    .from('flows')
    .select('public_slug')
    .eq('id', id)
    .single();

  if (fetchUpdatedError || !updatedFlow?.public_slug) {
    console.error('Error fetching updated flow:', fetchUpdatedError);
    return NextResponse.json({ error: 'Failed to get share link' }, { status: 500 });
  }

  return NextResponse.json({
    is_public: true,
    public_slug: updatedFlow.public_slug,
    share_url: `${process.env.NEXT_PUBLIC_APP_URL || ''}/flow/${updatedFlow.public_slug}`,
    expires_at: expiresAt.toISOString(),
  });
}

// DELETE - Make flow private
export async function DELETE(request: Request, { params }: RouteParams) {
  const { id } = await params;
  const user = await getUser();

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = await createServerSupabaseClient();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any;

  // Verify ownership
  const { data: existingFlow, error: fetchError } = await db
    .from('flows')
    .select('id')
    .eq('id', id)
    .eq('user_id', user.id)
    .single();

  if (fetchError || !existingFlow) {
    return NextResponse.json({ error: 'Flow not found' }, { status: 404 });
  }

  // Make private (keep the slug for potential re-sharing)
  const { error: updateError } = await db
    .from('flows')
    .update({
      is_public: false,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (updateError) {
    console.error('Error making flow private:', updateError);
    return NextResponse.json({ error: updateError.message }, { status: 500 });
  }

  return NextResponse.json({
    is_public: false,
    public_slug: null,
  });
}

// GET - Get share status
export async function GET(request: Request, { params }: RouteParams) {
  const { id } = await params;
  const user = await getUser();

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = await createServerSupabaseClient();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any;

  const { data: flow, error } = await db
    .from('flows')
    .select('id, is_public, public_slug')
    .eq('id', id)
    .eq('user_id', user.id)
    .single();

  if (error || !flow) {
    return NextResponse.json({ error: 'Flow not found' }, { status: 404 });
  }

  return NextResponse.json({
    is_public: flow.is_public,
    public_slug: flow.public_slug,
    share_url: flow.is_public && flow.public_slug
      ? `${process.env.NEXT_PUBLIC_APP_URL || ''}/flow/${flow.public_slug}`
      : null,
  });
}
